/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frame;

import help.*;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;

/**
 *
 * @author krzys
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    
    MainPanel panel = new MainPanel();
    
    int appWidth = 700;
    int appHeight = 650;
    
    int screenX = Toolkit.getDefaultToolkit().getScreenSize().width/2 - appWidth/2;
    int screenY = Toolkit.getDefaultToolkit().getScreenSize().height/2 - appHeight/2;
    
    JMenuBar menuBar = new JMenuBar();
    JMenu menuMain = new JMenu("HELP");
    JMenuItem readItem = new JMenuItem("How to read resistors");
    JMenuItem valueItem = new JMenuItem("Table of values");
    
    
    
    public MainFrame() {
       this.getContentPane().add(panel);
       this.setDefaultCloseOperation(EXIT_ON_CLOSE);
       this.setBounds(screenX, screenY, appWidth, appHeight);
       this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/image/icon3.png")));
       this.setTitle("Resistor Recognition Handler v1");
       this.setResizable(false);
       
       
       this.setJMenuBar(menuBar);
       
       initializeMenu();
    }

    private void initializeMenu()
    {
       menuBar.add(menuMain);
       menuMain.add(readItem);
       menuMain.add(valueItem);
       
       readItem.addActionListener(new ActionListener() {
           @Override
           public void actionPerformed(ActionEvent e) {
               HelpFrame helpFrame = new HelpFrame(650,360);
               CorrectOrderPanel orderPanel = new CorrectOrderPanel(helpFrame);
               helpFrame.setPanel(orderPanel);
           }
       });
       
       valueItem.addActionListener(new ActionListener() {
           @Override
           public void actionPerformed(ActionEvent e) {
                HelpFrame helpFrame = new HelpFrame(650,580);
                valueHelpPanel valuePanel = new valueHelpPanel(helpFrame);
                helpFrame.setPanel(valuePanel);
           }
       });
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
